<?php

namespace Database\Seeders;

use App\Modules\Phones\Models\PhoneBrand;
use App\Modules\Phones\Models\PhoneModel;
use Illuminate\Database\Seeder;

class PhoneModelSeeder extends Seeder
{
    public function run(): void
    {
        $brandModels = [
            'Apple' => [
                'iPhone XR',
                'iPhone XS',
                'iPhone XS Max',
                'iPhone 11',
                'iPhone 11 Pro',
                'iPhone 11 Pro Max',
                'iPhone 12',
                'iPhone 12 Mini',
                'iPhone 12 Pro',
                'iPhone 12 Pro Max',
                'iPhone 13',
                'iPhone 13 Mini',
                'iPhone 13 Pro',
                'iPhone 13 Pro Max',
                'iPhone 14',
                'iPhone 14 Plus',
                'iPhone 14 Pro',
                'iPhone 14 Pro Max',
                'iPhone 15',
                'iPhone 15 Plus',
                'iPhone 15 Pro',
                'iPhone 15 Pro Max',
                'iPhone 16',
                'iPhone 16 Plus',
                'iPhone 16 Pro',
                'iPhone 16 Pro Max',
                'iPhone 17',
                'iPhone 17 air',
                'iPhone 17 Pro',
                'iPhone 17 Pro Max',
            ],
            'Samsung' => [
                'Galaxy S9',
                'Galaxy S9+',
                'Galaxy S10e',
                'Galaxy S10',
                'Galaxy S10+',
                'Galaxy S10 5G',
                'Galaxy S10 Lite',
                'Galaxy S20',
                'Galaxy S20+',
                'Galaxy S20 Ultra',
                'Galaxy S20 FE 5G',
                'Galaxy S21',
                'Galaxy S21+',
                'Galaxy S21 Ultra',
                'Galaxy S21 FE 5G',
                'Galaxy S22',
                'Galaxy S22+',
                'Galaxy S22 Ultra',
                'Galaxy S23',
                'Galaxy S23+',
                'Galaxy S23 Ultra',
                'Galaxy S23 FE',
                'Galaxy S24',
                'Galaxy S24+',
                'Galaxy S24 Ultra',
                'Galaxy S25',
                'Galaxy S25+',
                'Galaxy S25 Ultra',
                'Galaxy Z Fold 4',
                'Galaxy Z Fold 5',
                'Galaxy Z Fold 6',
                'Galaxy Z Fold 7',
            ],
            'Xiaomi' => [
                'Xiaomi 17',
                'Xiaomi 17 Pro',
                'Xiaomi 17 Pro Max',
                'Xiaomi 15',
                'Xiaomi 15 Pro',
                'Xiaomi 15 Ultra',
                'Xiaomi 15T',
                'Xiaomi 15T Pro',
                'Xiaomi 14',
                'Xiaomi 14 Pro',
                'Xiaomi 14 Ultra',
                'Xiaomi 14T',
                'Xiaomi 14T Pro',
                'Xiaomi 13 Lite',
                'Xiaomi 13',
                'Xiaomi 13 Pro',
                'Xiaomi 13 Ultra',
                'Xiaomi 13T Series',
                'Xiaomi 13T',
                'Xiaomi 13T Pro',
                'Xiaomi 12',
                'Xiaomi 12 Pro',
                'Xiaomi 12S Ultra',
                'Xiaomi 12 Lite',
                'Xiaomi 12T',
                'Xiaomi 12X',
                'Xiaomi 11',
                'Xiaomi 11 Pro',
                'Xiaomi 11 Ultra',
                'Xiaomi 11 Lite',
                'Xiaomi 11 Lite 4G/5G',
                'Xiaomi 11T',
                'Xiaomi 11i',
            ],
            'Google Pixel' => [
                'Pixel 6',
                'Pixel 6 Pro',
                'Pixel 6a',
                'Pixel Fold',
                'Pixel 7',
                'Pixel 7 Pro',
                'Pixel 7a',
                'Pixel 8',
                'Pixel 8 Pro',
                'Pixel 8a',
                'Pixel 9',
                'Pixel 9 Pro',
                'Pixel 9 Pro XL',
                'Pixel 9 Pro Fold',
                'Pixel 9a',
                'Pixel 10',
                'Pixel 10 Pro',
                'Pixel 10 Pro XL',
                'Pixel 10 Pro Fold',
            ],
            'Huawei' => [
                'Huawei P60 Pro',
                'Huawei P60',
                'Huawei P50 Pro',
                'Huawei P50',
                'Huawei P50 Pocket',
                'Huawei P40 Pro+',
                'Huawei P40 Pro',
                'Huawei P40',
                'Huawei Mate 60 Pro+',
                'Huawei Mate 60 Pro',
                'Huawei Mate 60',
                'Huawei Mate 50 Pro',
                'Huawei Mate 50',
                'Huawei Mate X5',
                'Huawei Mate X3',
                'Huawei Mate Xs 2',
                'Huawei Nova 12 Pro',
                'Huawei Nova 12',
                'Huawei Nova 11 Pro',
                'Huawei Nova 11',
                'Huawei Nova 10 Pro',
                'Huawei Nova 10',
                'Huawei Nova 9 Pro',
                'Huawei Nova 9',
                'Huawei Nova Y91',
                'Huawei Nova Y90',
                'Huawei Nova Y70',
                'Huawei Nova Y61',
                'Huawei Enjoy 70 Pro',
                'Huawei Enjoy 60X',
            ],
            'Realme' => [
                'Realme GT 5 Pro',
                'Realme GT 5',
                'Realme GT 3',
                'Realme GT 2 Pro',
                'Realme GT 2',
                'Realme GT Neo 6',
                'Realme GT Neo 5',
                'Realme GT Neo 3',
                'Realme GT Neo 2',
                'Realme GT Master Edition',
                'Realme 12 Pro+',
                'Realme 12 Pro',
                'Realme 12',
                'Realme 11 Pro+',
                'Realme 11 Pro',
                'Realme 11',
                'Realme 10 Pro+',
                'Realme 10 Pro',
                'Realme 10',
                'Realme 9 Pro+',
                'Realme 9 Pro',
                'Realme 9',
                'Realme 9i',
                'Realme 8 Pro',
                'Realme 8',
                'Realme 8i',
                'Realme C67',
                'Realme C65',
                'Realme C63',
                'Realme C55',
                'Realme C53',
                'Realme C51',
                'Realme C35',
                'Realme C33',
                'Realme Narzo 70 Pro',
                'Realme Narzo 70',
                'Realme Narzo 60 Pro',
                'Realme Narzo 60',
                'Realme Narzo 50 Pro',
                'Realme Narzo 50',
            ],
            'Vivo' => [
                'Vivo X100 Pro',
                'Vivo X100',
                'Vivo X90 Pro+',
                'Vivo X90 Pro',
                'Vivo X90',
                'Vivo X80 Pro',
                'Vivo X80',
                'Vivo X70 Pro+',
                'Vivo X70 Pro',
                'Vivo X70',
                'Vivo V30 Pro',
                'Vivo V30',
                'Vivo V29 Pro',
                'Vivo V29',
                'Vivo V27 Pro',
                'Vivo V27',
                'Vivo V25 Pro',
                'Vivo V25',
                'Vivo V23 Pro',
                'Vivo V23',
                'Vivo V21',
                'Vivo Y100',
                'Vivo Y78',
                'Vivo Y56',
                'Vivo Y36',
                'Vivo Y27',
                'Vivo Y22',
                'Vivo Y16',
                'Vivo Y15',
                'Vivo Y02',
                'Vivo iQOO 12 Pro',
                'Vivo iQOO 12',
                'Vivo iQOO 11 Pro',
                'Vivo iQOO 11',
                'Vivo iQOO Z8',
                'Vivo iQOO Z7',
                'Vivo iQOO Neo 9 Pro',
                'Vivo iQOO Neo 7',
            ],
            'Oppo' => [
                'Oppo Find X6 Pro',
                'Oppo Find X6',
                'Oppo Find X5 Pro',
                'Oppo Find X5',
                'Oppo Find X3 Pro',
                'Oppo Find X3 Neo',
                'Oppo Find X3 Lite',
                'Oppo Find N3 Flip',
                'Oppo Find N3',
                'Oppo Find N2 Flip',
                'Oppo Find N2',
                'Oppo Reno 11 Pro',
                'Oppo Reno 11',
                'Oppo Reno 10 Pro+',
                'Oppo Reno 10 Pro',
                'Oppo Reno 10',
                'Oppo Reno 9 Pro+',
                'Oppo Reno 9 Pro',
                'Oppo Reno 9',
                'Oppo Reno 8 Pro',
                'Oppo Reno 8',
                'Oppo Reno 7 Pro',
                'Oppo Reno 7',
                'Oppo Reno 6 Pro',
                'Oppo Reno 6',
                'Oppo A98',
                'Oppo A78',
                'Oppo A58',
                'Oppo A38',
                'Oppo A18',
                'Oppo A96',
                'Oppo A76',
                'Oppo A57',
                'Oppo A17',
                'Oppo A16',
                'Oppo K11',
                'Oppo K10',
            ],
        ];

        foreach ($brandModels as $brandName => $models) {
            $brand = PhoneBrand::where('name', $brandName)->first();
            if (! $brand) {
                $this->command->warn("Brand '{$brandName}' not found. Run PhoneBrandSeeder first.");
                continue;
            }

            foreach ($models as $name) {
                PhoneModel::withTrashed()->updateOrCreate(
                    [
                        'phone_brand_id' => $brand->id,
                        'name' => $name,
                    ],
                    ['is_active' => false, 'deleted_at' => null]
                );
            }
        }
    }
}
