<?php

namespace App\Http\Controllers\Customer;

use App\Http\Controllers\Controller;
use App\Models\Invoice;
use App\Models\InvoiceRequest;
use App\Models\Order;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\View\View;
use Symfony\Component\HttpFoundation\StreamedResponse;

class DashboardController extends Controller
{
    private function ensureCustomer(): ?RedirectResponse
    {
        $user = auth()->user();

        if ($user->hasRole('super_admin') || $user->hasRole('admin') || $user->hasRole('staff')) {
            return redirect()->route('admin.dashboard');
        }

        return null;
    }

    public function index(): View|RedirectResponse
    {
        if ($redirect = $this->ensureCustomer()) {
            return $redirect;
        }

        $user = auth()->user();
        $pendingInvoiceRequests = InvoiceRequest::where('user_id', $user->id)
            ->where('status', 'pending')
            ->with('shipment')
            ->latest()
            ->get();
        // Recent orders: exclude delivered (only orders shipped yet to be delivered)
        $orders = Order::where('user_id', $user->id)
            ->where('status', '!=', 'delivered')
            ->with(['shipment.currentStage', 'currentStageOverride', 'invoice'])
            ->latest('id')
            ->take(10)
            ->get();

        // Orders in transit: only shipped, not yet delivered
        $trackableOrders = Order::where('user_id', $user->id)
            ->where('status', '!=', 'delivered')
            ->where(function ($q) {
                $q->whereNotNull('shipment_id')->orWhereNotNull('current_stage_id');
            })
            ->with(['shipment.currentStage', 'currentStageOverride'])
            ->latest('id')
            ->take(5)
            ->get();

        return view('customer.dashboard', compact('orders', 'trackableOrders', 'pendingInvoiceRequests'));
    }

    public function orders(Request $request): View|RedirectResponse
    {
        if ($redirect = $this->ensureCustomer()) {
            return $redirect;
        }

        $orders = Order::where('user_id', auth()->id())
            ->with(['shipment.currentStage', 'currentStageOverride', 'invoice', 'invoiceRequests' => fn ($q) => $q->where('user_id', auth()->id())])
            ->latest('id')
            ->paginate(15);

        return view('customer.orders', compact('orders'));
    }

    public function requestInvoice(Order $order): RedirectResponse
    {
        if ($redirect = $this->ensureCustomer()) {
            return $redirect;
        }
        if ($order->user_id !== auth()->id()) {
            abort(403);
        }
        if (! in_array($order->status, ['processing', 'shipped', 'delivered'])) {
            return back()->with('error', 'Invoice can be requested only for orders in processing or shipped.');
        }
        if (! $order->shipment_id) {
            return back()->with('error', 'Order must be assigned to a shipment before requesting invoice.');
        }
        $uninvoicedOrders = Order::where('shipment_id', $order->shipment_id)
            ->where('user_id', auth()->id())
            ->whereDoesntHave('invoice')
            ->whereIn('status', ['processing', 'shipped', 'delivered'])
            ->count();
        if ($uninvoicedOrders === 0) {
            return back()->with('status', 'Invoice already generated for this shipment. Download from Invoices page.');
        }
        InvoiceRequest::firstOrCreate(
            ['shipment_id' => $order->shipment_id, 'user_id' => auth()->id()],
            ['status' => 'pending']
        );
        return back()->with('status', 'Invoice requested for ' . $uninvoicedOrders . ' item(s) in this shipment. It will be available once generated by admin.');
    }

    public function confirmDelivery(Order $order): RedirectResponse
    {
        if ($redirect = $this->ensureCustomer()) {
            return $redirect;
        }

        if ($order->user_id !== auth()->id()) {
            abort(403);
        }

        if (!$order->canCustomerConfirmDelivery()) {
            return back()->with('error', 'You can only confirm delivery when your package is dispatched or delivered.');
        }

        $deliveredStage = \App\Models\TrackingStage::where('position', 6)->first();
        $order->update([
            'status' => 'delivered',
            'current_stage_id' => $deliveredStage?->id,
        ]);

        return back()->with('status', 'Thank you! Your order has been marked as received.');
    }

    public function tracking(): View|RedirectResponse
    {
        if ($redirect = $this->ensureCustomer()) {
            return $redirect;
        }

        // Only shipped, not yet delivered
        $orders = Order::where('user_id', auth()->id())
            ->where('status', '!=', 'delivered')
            ->where(function ($q) {
                $q->whereNotNull('shipment_id')->orWhereNotNull('current_stage_id');
            })
            ->with(['shipment.currentStage', 'currentStageOverride'])
            ->latest('id')
            ->paginate(15);

        return view('customer.tracking', compact('orders'));
    }

    public function invoices(): View|RedirectResponse
    {
        if ($redirect = $this->ensureCustomer()) {
            return $redirect;
        }

        $invoices = Invoice::where('user_id', auth()->id())
            ->latest('id')
            ->paginate(20);

        return view('customer.invoices', compact('invoices'));
    }

    /** Secured invoice download – prevents direct file URLs that could be guessed */
    public function downloadInvoice(Invoice $invoice): StreamedResponse|RedirectResponse
    {
        if ($redirect = $this->ensureCustomer()) {
            return $redirect;
        }
        if ($invoice->user_id !== (int) auth()->id()) {
            abort(403);
        }
        if (! $invoice->pdf_path || str_contains($invoice->pdf_path, '..')) {
            return back()->with('error', 'Invoice file not available.');
        }
        $path = $invoice->pdf_path;

        try {
            $fullPath = storage_path('app/public/' . str_replace(['\\', '..'], ['/', ''], $path));
            if (is_file($fullPath)) {
                return response()->file($fullPath, [
                    'Content-Type' => 'application/pdf',
                    'Content-Disposition' => 'attachment; filename="invoice-' . preg_replace('/[^a-zA-Z0-9\-_.]/', '', $invoice->invoice_number) . '.pdf"',
                ]);
            }
            if (Storage::disk('public')->exists($path)) {
                return Storage::disk('public')->download(
                    $path,
                    'invoice-' . $invoice->invoice_number . '.pdf',
                    ['Content-Type' => 'application/pdf']
                );
            }
        } catch (\Throwable $e) {
            report($e);
        }

        return back()->with('error', 'Invoice file not found.');
    }
}
