<?php

namespace App\Http\Controllers\Customer;

use App\Http\Controllers\Controller;
use App\Models\Invoice;
use App\Models\InvoiceRequest;
use App\Models\Order;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\View\View;
use Symfony\Component\HttpFoundation\StreamedResponse;

class DashboardController extends Controller
{
    private function ensureCustomer(): ?RedirectResponse
    {
        $user = auth()->user();

        if ($user->hasRole('super_admin') || $user->hasRole('admin') || $user->hasRole('staff')) {
            return redirect()->route('admin.dashboard');
        }

        return null;
    }

    public function index(): View|RedirectResponse
    {
        if ($redirect = $this->ensureCustomer()) {
            return $redirect;
        }

        $user = auth()->user();
        $pendingInvoiceRequests = InvoiceRequest::where('user_id', $user->id)
            ->where('status', 'pending')
            ->with('shipment')
            ->latest()
            ->get();
        // Recent orders: exclude delivered (only orders shipped yet to be delivered)
        $orders = Order::where('user_id', $user->id)
            ->where('status', '!=', 'delivered')
            ->with(['shipment.currentStage', 'currentStageOverride', 'invoice'])
            ->latest('id')
            ->take(5)
            ->get();

        // Orders in transit: only shipped, not yet delivered
        $trackableOrders = Order::where('user_id', $user->id)
            ->where('status', '!=', 'delivered')
            ->where(function ($q) {
                $q->whereNotNull('shipment_id')->orWhereNotNull('current_stage_id');
            })
            ->with(['shipment.currentStage', 'currentStageOverride'])
            ->latest('id')
            ->take(3)
            ->get();

        $pendingOrdersCount = Order::where('user_id', $user->id)
            ->whereIn('status', ['pending', 'pending_approval', 'processing', 'shipped'])
            ->count();
        $inTransitCount = Order::where('user_id', $user->id)
            ->where('status', '!=', 'delivered')
            ->where(function ($q) {
                $q->whereNotNull('shipment_id')->orWhereNotNull('current_stage_id');
            })
            ->count();

        return view('customer.dashboard', compact(
            'orders',
            'trackableOrders',
            'pendingInvoiceRequests',
            'pendingOrdersCount',
            'inTransitCount'
        ));
    }

    public function orders(Request $request): View|RedirectResponse
    {
        if ($redirect = $this->ensureCustomer()) {
            return $redirect;
        }

        $orders = Order::where('user_id', auth()->id())
            ->with(['shipment.currentStage', 'currentStageOverride', 'invoice', 'invoiceRequests' => fn ($q) => $q->where('user_id', auth()->id())])
            ->latest('id')
            ->paginate(15);

        $highlightOrderId = (int) $request->query('order', 0);

        return view('customer.orders', compact('orders', 'highlightOrderId'));
    }

    public function requestInvoice(Order $order): RedirectResponse
    {
        if ($redirect = $this->ensureCustomer()) {
            return $redirect;
        }
        if ($order->user_id !== auth()->id()) {
            abort(403);
        }
        if (! in_array($order->status, ['processing', 'shipped', 'delivered'])) {
            return back()->with('error', 'Invoice can be requested only for orders in processing or shipped.');
        }
        if (! $order->shipment_id) {
            return back()->with('error', 'Order must be assigned to a shipment before requesting invoice.');
        }
        $uninvoicedOrders = Order::where('shipment_id', $order->shipment_id)
            ->where('user_id', auth()->id())
            ->whereDoesntHave('invoice')
            ->whereIn('status', ['processing', 'shipped', 'delivered'])
            ->count();
        if ($uninvoicedOrders === 0) {
            return back()->with('status', 'Invoice already generated for this shipment. Download from Invoices page.');
        }
        InvoiceRequest::firstOrCreate(
            ['shipment_id' => $order->shipment_id, 'user_id' => auth()->id()],
            ['status' => 'pending']
        );
        return back()->with('status', 'Invoice requested for ' . $uninvoicedOrders . ' item(s) in this shipment. It will be available once generated by admin.');
    }

    public function confirmDelivery(Order $order): RedirectResponse
    {
        if ($redirect = $this->ensureCustomer()) {
            return $redirect;
        }

        if ($order->user_id !== auth()->id()) {
            abort(403);
        }

        if (!$order->canCustomerConfirmDelivery()) {
            return back()->with('error', 'You can only confirm delivery when your package is dispatched or delivered.');
        }

        $deliveredStage = \App\Models\TrackingStage::where('position', 6)->first();
        $order->update([
            'status' => 'delivered',
            'current_stage_id' => $deliveredStage?->id,
        ]);

        return back()->with('status', 'Thank you! Your order has been marked as received.');
    }

    public function tracking(Request $request): View|RedirectResponse
    {
        if ($redirect = $this->ensureCustomer()) {
            return $redirect;
        }

        // Only shipped, not yet delivered
        $orders = Order::where('user_id', auth()->id())
            ->where('status', '!=', 'delivered')
            ->where(function ($q) {
                $q->whereNotNull('shipment_id')->orWhereNotNull('current_stage_id');
            })
            ->with(['shipment.currentStage', 'currentStageOverride'])
            ->latest('id')
            ->paginate(15);

        $highlightOrderId = (int) $request->query('order', 0);

        return view('customer.tracking', compact('orders', 'highlightOrderId'));
    }

    public function invoices(): View|RedirectResponse
    {
        if ($redirect = $this->ensureCustomer()) {
            return $redirect;
        }

        try {
            $invoices = Invoice::where('user_id', auth()->id())
                ->latest('id')
                ->paginate(20);

            return view('customer.invoices', compact('invoices'));
        } catch (\Throwable $e) {
            report($e);
            $invoices = new \Illuminate\Pagination\LengthAwarePaginator([], 0, 20);
            return view('customer.invoices', compact('invoices'))->with('error', 'Unable to load invoices. Please try again.');
        }
    }

    /**
     * Invoice download – minimal path to avoid 500.
     * Uses numeric id (no route model binding), single path: storage/app/public/invoices/invoice-XXX.pdf.
     *
     * Note: no return type hint to avoid PHP type errors when returning a normal Response instance.
     */
    public function downloadInvoice(int $id)
    {
        try {
            if ($redirect = $this->ensureCustomer()) {
                return $redirect;
            }

            $userId = (int) auth()->id();
            $invoice = Invoice::where('id', $id)->where('user_id', $userId)->first();
            if (! $invoice) {
                return back()->with('error', 'Invoice not found.');
            }

            $invoiceNumber = trim((string) ($invoice->invoice_number ?? ''));
            $safe = preg_replace('/[^a-zA-Z0-9\-_.]/', '', $invoiceNumber);
            $filename = 'invoice-' . $safe . '.pdf';
            $dir = storage_path('app/public') . DIRECTORY_SEPARATOR . 'invoices';
            $path = $dir . DIRECTORY_SEPARATOR . $filename;

            if (is_file($path)) {
                $content = @file_get_contents($path);
                if ($content !== false && $content !== '') {
                    return response($content, 200, [
                        'Content-Type' => 'application/pdf',
                        'Content-Disposition' => 'attachment; filename="' . $filename . '"',
                    ]);
                }
            }

            $pathFromDb = $invoice->pdf_path;
            if (is_string($pathFromDb) && $pathFromDb !== '') {
                $altPath = $dir . DIRECTORY_SEPARATOR . basename(str_replace(['\\', '/'], DIRECTORY_SEPARATOR, $pathFromDb));
                if (is_file($altPath)) {
                    $content = @file_get_contents($altPath);
                    if ($content !== false && $content !== '') {
                        return response($content, 200, [
                            'Content-Type' => 'application/pdf',
                            'Content-Disposition' => 'attachment; filename="' . $filename . '"',
                        ]);
                    }
                }
            }
        } catch (\Throwable $e) {
            report($e);
            return back()->with('error', 'Unable to load invoice. Please try again later.');
        }

        return back()->with('error', 'Invoice file not found.');
    }
}
