<?php

return [
    /*
     * Nigeria states and a comprehensive list of cities.
     * This supports type-to-search dropdowns and cascading city suggestions.
     * Do not replace with a shorter list – keep this complete list.
     */
    'states_cities' => [
        'Abia' => ['Aba', 'Umuahia', 'Ohafia', 'Arochukwu', 'Bende', 'Ikwuano', 'Isiala-Ngwa', 'Isuikwuato', 'Umunneochi', 'Obi Ngwa', 'Abiriba', 'Amaeke', 'Igbere', 'Nbawsi', 'Eluoma', 'Alayi', 'Ohuhu', 'Umukabia'],
        'Adamawa' => ['Yola', 'Mubi', 'Jimeta', 'Numan', 'Ganye', 'Gombi', 'Guyuk', 'Hong', 'Jada', 'Maiha', 'Mayo-Belwa', 'Michika', 'Demsa', 'Fufore', 'Girei', 'Shelleng', 'Song', 'Madagali', 'Toungo', 'Lamurde'],
        'Akwa Ibom' => ['Uyo', 'Eket', 'Ikot Ekpene', 'Oron', 'Abak', 'Ikot Abasi', 'Etinan', 'Ibeno', 'Itu', 'Mkpat-Enin', 'Nsit Ubium', 'Ukanafun', 'Uruan', 'Ibiono-Ibom', 'Essien Udim', 'Onna', 'Obot Akara', 'Oruk Anam', 'Ika', 'Mbo', 'Udung Uko'],
        'Anambra' => ['Awka', 'Onitsha', 'Nnewi', 'Ekwulobia', 'Obosi', 'Ogidi', 'Abagana', 'Alor', 'Atani', 'Nkpor', 'Nnobi', 'Adazi Nnukwu', 'Adazi Enu', 'Aguleri', 'Agulu', 'Awkuzu', 'Ihiala', 'Oko', 'Uli', 'Ojoto', 'Okija', 'Abba', 'Adazi Ani', 'Amawbia', 'Nando', 'Nawfia', 'Neni', 'Ogbunike', 'Ogboji', 'Ogbunka', 'Owerre-Ezukala', 'Umunze'],
        'Bauchi' => ['Bauchi', 'Azare', 'Misau', 'Jama\'are', 'Alkaleri', 'Ningi', 'Dass', 'Darazo', 'Gamawa', 'Tafawa Balewa', 'Toro', 'Warji', 'Zaki', 'Kari', 'Dindima', 'Lere', 'Katagum', 'Itas/Gadau', 'Kirfi', 'Shira', 'Dambam'],
        'Bayelsa' => ['Yenagoa', 'Brass', 'Ogbia', 'Sagbama', 'Nembe', 'Ekeremor', 'Kolokuma/Opokuma', 'Southern Ijaw', 'Akassa', 'Amassoma', 'Kaiama', 'Odi', 'Oporoma', 'Oloibiri', 'Koluama', 'Opokuma', 'Peremabiri', 'Tubodiri'],
        'Benue' => ['Makurdi', 'Gboko', 'Otukpo', 'Katsina-Ala', 'Vandeikya', 'Ugbokolo', 'Obi', 'Otukpa', 'Igbor', 'Takum', 'Ushongo', 'Adikpo', 'Buruku', 'Guma', 'Gwer East', 'Gwer West', 'Kwande', 'Logo', 'Ogbadibo', 'Ohimini', 'Oju', 'Okpokwu', 'Tarka', 'Agila'],
        'Borno' => ['Maiduguri', 'Biu', 'Dikwa', 'Monguno', 'Bama', 'Damboa', 'Chibok', 'Konduga', 'Gwoza', 'Askira/Uba', 'Hawul', 'Kaga', 'Kukawa', 'Mafa', 'Magumeri', 'Marte', 'Mobbar', 'Ngala', 'Nganzai', 'Shani', 'Abadam', 'Guzamala', 'Jere', 'Kala/Balge', 'Kwaya Kusar'],
        'Cross River' => ['Calabar', 'Ikom', 'Ogoja', 'Ugep', 'Obudu', 'Obubra', 'Akamkpa', 'Akpabuyo', 'Biase', 'Bekwarra', 'Obanliku', 'Boki', 'Etung', 'Yakuur', 'Odukpani', 'Abi', 'Igede', 'Ikang', 'Creek Town', 'Duke Town', 'Ekori'],
        'Delta' => ['Asaba', 'Warri', 'Sapele', 'Ughelli', 'Effurun', 'Abraka', 'Ozoro', 'Kwale', 'Burutu', 'Koko', 'Oghara', 'Agbor', 'Anioma', 'Bomadi', 'Patani', 'Ukwuani', 'Orerokpe', 'Akwukwu-Igbo', 'Okpanam', 'Onicha', 'Oshimili', 'Ndokwa', 'Okpe', 'Ethiope', 'Udu'],
        'Ebonyi' => ['Abakaliki', 'Afikpo', 'Onueke', 'Ishiagu', 'Edda', 'Ikwo', 'Nkalagu', 'Okposi', 'Onicha', 'Amasiri', 'Uburu', 'Unwana', 'Ezza', 'Ivo', 'Ohaozara', 'Ishielu', 'Ebonyi', 'Ohaukwu'],
        'Edo' => ['Benin City', 'Auchi', 'Ekpoma', 'Uromi', 'Abudu', 'Afuze', 'Ewu', 'Fugar', 'Ibillo', 'Igarra', 'Igueben', 'Irrua', 'Okpella', 'Sabongida-Ora', 'Ubiaja', 'Agenebode', 'Ughoton', 'Jattu', 'Uzebba', 'Esan', 'Akoko-Edo', 'Etsako', 'Oredo', 'Orhionmwon', 'Ovia'],
        'Ekiti' => ['Ado-Ekiti', 'Ikere-Ekiti', 'Ilawe-Ekiti', 'Efon', 'Emure', 'Ijero', 'Ikole', 'Ise', 'Iye', 'Iyin', 'Aramoko', 'Ayedun', 'Gbonyin', 'Ido-Osi', 'Igede', 'Moba', 'Oye', 'Ekiti East', 'Ekiti South-West', 'Ekiti West', 'Aisegba', 'Esinmu', 'Esun', 'Ikogosi', 'Ajebandele', 'Esure', 'Alafe', 'Ewu', 'Ikoro', 'Ara', 'Ijare', 'Ogotun', 'Okemesi', 'Omuo'],
        'Enugu' => ['Enugu', 'Nsukka', 'Oji River', 'Awgu', 'Udi', 'Ninth Mile', 'Agbani', 'Adani', 'Ake-Eze', 'Aku', 'Amagunze', 'Eha Amufu', 'Enugu-Ezike', 'Ikem', 'Obolo-Eke', 'Ogurugu', 'Opi', 'Abor', 'Achi', 'Agbogugu', 'Agbudu', 'Akpugo', 'Akwuke', 'Edem', 'Emene', 'Ngwo', 'Ohum', 'Owo', 'Uzo-Uwani', 'Ezeagu', 'Igbo-Etiti', 'Igbo-Eze', 'Isi-Uzo', 'Nkanu', 'Udenu'],
        'Gombe' => ['Gombe', 'Kumo', 'Billiri', 'Dukku', 'Kaltungo', 'Deba', 'Nafada', 'Bajoga', 'Pindiga', 'Garko', 'Dadin Kowa', 'Filiya', 'Kashere', 'Shinga', 'Panda', 'Guji', 'Wange', 'Bojude', 'Birin-Fulani', 'Dadinkowa', 'Yamaltu', 'Funakaye', 'Kwami', 'Akko', 'Balanga', 'Shongom'],
        'Imo' => ['Owerri', 'Orlu', 'Okigwe', 'Mbaise', 'Oguta', 'Naze', 'Amaimo', 'Emekuku', 'Etiti', 'Ideato', 'Ihiagwa', 'Mgbidi', 'Nkwerre', 'Obowu', 'Umudim', 'Uzoagba', 'Ihuo', 'Nnarambia', 'Umuagwo', 'Mbieri', 'Orsu', 'Ezeoke', 'Nsu', 'Ehime Mbano', 'Isu', 'Mbaitoli', 'Oru', 'Ohaji/Egbema', 'Onuimo', 'Njaba', 'Oguta', 'Ohaji'],
        'Jigawa' => ['Dutse', 'Hadejia', 'Gumel', 'Kazaure', 'Birnin Kudu', 'Ringim', 'Guri', 'Babura', 'Dawa', 'Gantsa', 'Gujungu', 'Jahun', 'Maigatari', 'Malam Madori', 'Gagarawa', 'Kiyawa', 'Sule Tankarkar', 'Maje', 'Basirka', 'Falgeri', 'Ahoto', 'Garki', 'Kanya Babba', 'Madachi', 'Malummaduri', 'Marma', 'Teshegwa', 'Gwaram', 'Giwa', 'Kaugama', 'Birin Magaji'],
        'Kaduna' => ['Kaduna', 'Zaria', 'Kafanchan', 'Saminaka', 'Kachia', 'Kagoro', 'Zonkwa', 'Jaji', 'Birnin Gwari', 'Giwa', 'Ikara', 'Kajuru', 'Kaura', 'Kauru', 'Kubau', 'Kudan', 'Lere', 'Makarfi', 'Sabon Gari', 'Sanga', 'Soba', 'Zangon Kataf', 'Igabi', 'Jaba', 'Jema\'a', 'Chikun', 'Kaduna North', 'Kaduna South', 'Kagarko', 'Karko'],
        'Kano' => ['Kano', 'Wudil', 'Gaya', 'Bichi', 'Dala', 'Dambatta', 'Garzo', 'Gwale', 'Gwarzo', 'Hotoro', 'Kabuga', 'Karaye', 'Nassarawa', 'Fagge', 'Tarauni', 'Kano Municipal', 'Kumbotso', 'Kura', 'Madobi', 'Makoda', 'Minjibir', 'Rano', 'Rimin Gado', 'Rogo', 'Shanono', 'Sumaila', 'Takai', 'Tsanyawa', 'Tudun Wada', 'Ungogo', 'Warawa', 'Dawakin Kudu', 'Dawakin Tofa', 'Gabasawa', 'Gezawa', 'Garko', 'Albasu', 'Bagwai', 'Bebeji', 'Ajingi'],
        'Katsina' => ['Katsina', 'Daura', 'Funtua', 'Malumfashi', 'Bakori', 'Batagarawa', 'Jibia', 'Kankia', 'Zango', 'Dutsin-Ma', 'Kankara', 'Mani', 'Mashi', 'Matazu', 'Musawa', 'Rimi', 'Sabuwa', 'Safana', 'Sandamu', 'Charanchi', 'Dan Musa', 'Dandume', 'Danja', 'Dutsi', 'Faskari', 'Ingawa', 'Kafur', 'Kurfi', 'Kusada', 'Mai\'Adua', 'Baure', 'Bindawa', 'Batsari', 'Zango'],
        'Kebbi' => ['Birnin Kebbi', 'Argungu', 'Yauri', 'Zuru', 'Jega', 'Bagudo', 'Kamba', 'Koko', 'Bunza', 'Dakingari', 'Kangiwa', 'Arewa Dandi', 'Suru', 'Dandi', 'Fakai', 'Gwandu', 'Kalgo', 'Mahuta', 'Maiyama', 'Ribah', 'Sakaba', 'Shanga', 'Wara', 'Augie', 'Danko', 'Wasaugu'],
        'Kogi' => ['Lokoja', 'Okene', 'Idah', 'Kabba', 'Ankpa', 'Anyigba', 'Dekina', 'Egbe', 'Itakpe', 'Koton-Karfe', 'Ajaokuta', 'Ogidi', 'Ogaminan', 'Ijumu', 'Mopamuro', 'Ofu', 'Ogori', 'Magongo', 'Adavi', 'Bassa', 'Ibaji', 'Igalamela-Odolu', 'Kogi', 'Lokoja', 'Okehi', 'Olomoro', 'Omala', 'Yagba East', 'Yagba West'],
        'Kwara' => ['Ilorin', 'Offa', 'Omu-Aran', 'Jebba', 'Afon', 'Ajasse-Ipo', 'Buari', 'Edidi', 'Erin-Ile', 'Esie', 'Gure', 'Igbaja', 'Kaiama', 'Lafiagi', 'Oke-Onigbin', 'Osi', 'Share', 'Patigi', 'Iloffa', 'Ekiti', 'Oke Oyi', 'Chikanda', 'Gwanara', 'Ilesha Baruba', 'Budo-Ota', 'Budo-Pupa', 'Iwo', 'Iwonte', 'Iyabudo', 'Aboto Alfa', 'Aran-Orin', 'Arandun', 'Babanloma', 'Edidi', 'Igbonla', 'Ijara', 'Oro-Ago', 'Osi-Ilorin', 'Pamo', 'Shao'],
        'Lagos' => ['Ikeja', 'Lekki', 'Surulere', 'Yaba', 'Ajah', 'Ikorodu', 'Epe', 'Badagry', 'Victoria Island', 'Lagos Island', 'Agege', 'Alimosho', 'Apapa', 'Ifako-Ijaye', 'Kosofe', 'Mushin', 'Oshodi-Isolo', 'Shomolu', 'Ajeromi-Ifelodun', 'Amuwo-Odofin', 'Eti-Osa', 'Ibeju-Lekki', 'Lagos Mainland', 'Ojo', 'Somolu', 'Abule Egba', 'Agbado', 'Akowonjo', 'Ejigbo', 'Festac Town', 'Gbagada', 'Igando', 'Ikotun', 'Isolo', 'Ketu', 'Mile 2', 'Ogba', 'Ojodu', 'Okota', 'Orile', 'Oworonshoki', 'Yaba', 'Ilupeju', 'Maryland', 'Ogudu', 'Ojota', 'Anthony', 'Gbagada', 'Palmgrove', 'Fadeyi', 'Jibowu', 'Ebute Metta', 'Apapa', 'Kirikiri', 'Amuwo', 'Festac', 'Mile 2', 'Ojo', 'Alaba', 'Ijanikin', 'Ojo', 'Agbara', 'Sango', 'Ota', 'Ifo', 'Sagamu', 'Ikorodu Town', 'Eredo', 'Odogunyan', 'Mowe', 'Ibafo'],
        'Nasarawa' => ['Lafia', 'Keffi', 'Akwanga', 'Karu', 'Nasarawa', 'Doma', 'Wamba', 'Eggon', 'Kokona', 'Awe', 'Keana', 'Toto', 'Mararaba', 'Maraba', 'Nyanya', 'Karu', 'Gwarinpa', 'Dutse', 'Keffi', 'Kokona', 'Akwanga', 'Lafia', 'Wamba', 'Nasarawa', 'Doma', 'Awe', 'Keana', 'Toto', 'Obi', 'Udege', 'Loko', 'Mada'],
        'Niger' => ['Minna', 'Bida', 'Suleja', 'Kontagora', 'Baro', 'Zungeru', 'Tegina', 'Mokwa', 'Lapai', 'Agaie', 'Rafi', 'Paikoro', 'Mashegu', 'Mariga', 'Magama', 'Muyi', 'Chanchaga', 'Bosso', 'Katcha', 'Rijau', 'Wasagu/Danko', 'Borgu', 'Edati', 'Gbako', 'Gurara', 'Kontagora', 'Lapai', 'Lavun', 'Mokwa', 'Moya', 'Suleja', 'Tafa', 'Wushishi', 'Agaie', 'Bida', 'Kontagora', 'Minna', 'Suleja', 'Zungeru'],
        'Ogun' => ['Abeokuta', 'Ijebu-Ode', 'Sagamu', 'Ota', 'Ifo', 'Ilaro', 'Ijebu Igbo', 'Ayetoro', 'Agbara', 'Ajebo', 'Ago-Iwoye', 'Akute', 'Atan', 'Ewekoro', 'Idiroko', 'Imeko', 'Ipokia', 'Iperu', 'Isara', 'Obafemi Owode', 'Odeda', 'Odogbolu', 'Remo North', 'Shagamu', 'Yewa North', 'Yewa South', 'Ado-Odo', 'Sango-Ota', 'Mowe', 'Ibafo', 'Arepo', 'Magboro', 'Owode', 'Lafenwa', 'Ita Iyalode', 'Oke Ogun', 'Imala', 'Ake', 'Oke-Ilewo', 'Panseke', 'Quarters', 'Kuto', 'Omida', 'Iberekodo', 'Oke-Ilewo', 'Sapon', 'Adatan', 'FUTA South', 'FUTA North', 'Isale-Igbein', 'Oke-Igbein', 'Oke-Ilewo', 'Ibara', 'Ijeun', 'Itoku', 'Oke-Ilewo', 'Igbore', 'Ijemo', 'Oke-Ilewo', 'Ibara', 'Ijeun', 'Itoku'],
        'Ondo' => ['Akure', 'Ondo', 'Owo', 'Ikare', 'Okitipupa', 'Ile-Oluji', 'Ode-Irele', 'Ifon', 'Igbara-Oke', 'Irele', 'Owena', 'Idanre', 'Oka', 'Igbotako', 'Ode-Aye', 'Ilutitun', 'Arigidi-Akoko', 'Ikare-Akoko', 'Oka-Akoko', 'Ijare', 'Ilara-Mokin', 'Akungba', 'Ose', 'Odigbo', 'Ondo East', 'Ondo West', 'Ilaje', 'Ile Oluji/Okeigbo', 'Irele', 'Odigbo', 'Okitipupa', 'Ondo', 'Ose', 'Owo', 'Akoko North-East', 'Akoko North-West', 'Akoko South-East', 'Akoko South-West', 'Akure North', 'Akure South', 'Idanre', 'Ifedore', 'Ile Oluji/Okeigbo', 'Odigbo', 'Ondo East', 'Ondo West'],
        'Osun' => ['Osogbo', 'Ile-Ife', 'Ilesa', 'Ede', 'Iwo', 'Ikirun', 'Ila Orangun', 'Ikire', 'Ejigbo', 'Esa-Oke', 'Ilobu', 'Inisa', 'Ipetumodu', 'Gbongan', 'Iree', 'Odeomu', 'Ifetedo', 'Modakeke', 'Iperindo', 'Apomu', 'Ibodi', 'Ikoyi', 'Otan Ayegbaju', 'Otan Ile', 'Bode-Osi', 'Ishaga', 'Ile-Ife', 'Ilesa', 'Osogbo', 'Ede', 'Iwo', 'Ikirun', 'Ila Orangun', 'Ikire', 'Ejigbo', 'Esa-Oke', 'Ilobu', 'Inisa', 'Gbongan', 'Iree', 'Odeomu', 'Ifetedo', 'Ipetumodu', 'Apomu', 'Ibodi', 'Ikoyi', 'Otan Ayegbaju', 'Otan Ile', 'Bode-Osi', 'Ishaga', 'Atakunmosa', 'Boluwaduro', 'Boripe', 'Ede North', 'Ede South', 'Egbedore', 'Ejigbo', 'Ife Central', 'Ife East', 'Ife North', 'Ife South', 'Ifedayo', 'Ifelodun', 'Ila', 'Ilesa East', 'Ilesa West', 'Irepodun', 'Irewole', 'Isokan', 'Iwo', 'Obokun', 'Odo-Otin', 'Ola-Oluwa', 'Olorunda', 'Oriade', 'Orolu', 'Osogbo'],
        'Oyo' => ['Ibadan', 'Ogbomoso', 'Oyo', 'Iseyin', 'Saki', 'Igboho', 'Lalupon', 'Kisi', 'Okeho', 'Fiditi', 'Ilora', 'Eruwa', 'Igbo-Ora', 'Akanran', 'Egbeda', 'Idi Ayunre', 'Igangan', 'Iresa Adu', 'Ado-Awaye', 'Ago-Amodu', 'Moniya', 'Akinyele', 'Afijio', 'Atiba', 'Atisbo', 'Ibarapa Central', 'Ibarapa East', 'Ibarapa North', 'Ido', 'Irepo', 'Iwajowa', 'Kajola', 'Lagelu', 'Ogo Oluwa', 'Olorunsogo', 'Oluyole', 'Ona Ara', 'Orelope', 'Ori Ire', 'Oyo East', 'Oyo West', 'Saki East', 'Saki West', 'Surulere', 'Itesiwaju', 'Iseyin', 'Kajola', 'Okeho', 'Igboho', 'Sepeteri', 'Tede', 'Ago Are', 'Aran', 'Otu', 'Oke-Ogun', 'Ipapo', 'Kishi', 'Ago Amodu', 'Eruwa', 'Lanlate', 'Tanti', 'Ojoo', 'Challenge', 'Bodija', 'Dugbe', 'Mokola', 'Agodi', 'Gate', 'Ring Road', 'Iyaganku', 'Oke-Ado', 'Oke-Offa', 'Sango', 'Omi Adio', 'Eleyele', 'Oluyole Estate', 'Jericho', 'GRA', 'New Garage', 'Oje', 'Bashorun', 'Oke-Bola', 'Aleshinloye', 'Beere', 'Mapo', 'Oke-Padi', 'Oja Oba', 'Oke-Bola', 'Aleshinloye', 'Beere', 'Mapo', 'Oke-Padi', 'Oja Oba'],
        'Plateau' => ['Jos', 'Bukuru', 'Pankshin', 'Shendam', 'Barkin Ladi', 'Mangu', 'Langtang', 'Vom', 'Kuru', 'Riyom', 'Bokkos', 'Wase', 'Bassa', 'Mikang', 'Kanam', 'Kanke', 'Qua\'an Pan', 'Riyom', 'Jos East', 'Jos North', 'Jos South', 'Mangu', 'Barkin Ladi', 'Bokkos', 'Kanam', 'Kanke', 'Langtang North', 'Langtang South', 'Mangu', 'Mikang', 'Pankshin', 'Qua\'an Pan', 'Riyom', 'Shendam', 'Wase'],
        'Rivers' => ['Port Harcourt', 'Obio-Akpor', 'Bonny', 'Ahoada', 'Buguma', 'Okrika', 'Eleme', 'Omoku', 'Bori', 'Degema', 'Abonnema', 'Opobo', 'Andoni', 'Asari-Toru', 'Akuku-Toru', 'Emuoha', 'Etche', 'Gokana', 'Ikwerre', 'Khana', 'Ogba/Egbema/Ndoni', 'Ogu/Bolo', 'Okrika', 'Omuma', 'Tai', 'Abalama', 'Akinima', 'Akpajo', 'Alakahia', 'Aluu', 'Ataba', 'Bane', 'Bille', 'Choba', 'Diobu', 'Eliozu', 'Elelenwo', 'Eneka', 'Igbo-Etiti', 'Igwuruta', 'Isiokpo', 'Ogbogoro', 'Ogboama', 'Oguta', 'Okpogho', 'Okwuta', 'Omunegwu', 'Onne', 'Rumuokoro', 'Rumuokwuta', 'Trans-Amadi', 'Woji', 'Yokohama'],
        'Sokoto' => ['Sokoto', 'Wamako', 'Tambuwal', 'Gwadabawa', 'Bodinga', 'Gada', 'Ilela', 'Wurno', 'Yabo', 'Binji', 'Dange-Shuni', 'Goronyo', 'Gudu', 'Isa', 'Kware', 'Rabah', 'Sabon Birni', 'Shagari', 'Silame', 'Tangaza', 'Tureta', 'Zurmi', 'Kebbe', 'Illela', 'Gada', 'Wurno', 'Yabo', 'Binji', 'Dange', 'Shuni', 'Goronyo', 'Gudu', 'Isa', 'Kware', 'Rabah', 'Sabon Birni', 'Shagari', 'Silame', 'Tangaza', 'Tureta', 'Zurmi', 'Kebbe', 'Illela', 'Salame', 'Gigane', 'Asara', 'Chimmola', 'Mamman Suka', 'Gidan Kaya', 'Tambagarka', 'G-Tudu', 'Arbukwe', 'Gwazange', 'Boto', 'Makwa'],
        'Taraba' => ['Jalingo', 'Wukari', 'Bali', 'Serti', 'Ibi', 'Gashaka', 'Kurmi', 'Takum', 'Zing', 'Lau', 'Donga', 'Gassol', 'Karim Lamido', 'Sardauna', 'Ussa', 'Yorro', 'Ardo Kola', 'Baissa', 'Beli', 'Gembu', 'Mutum Biyu', 'Riti', 'Chinkai', 'Bantaje', 'Gindin Dorowa', 'Anguwan Rogo', 'Kashin', 'Donnada', 'Kanawa', 'Masweah', 'Lushi', 'Dampar'],
        'Yobe' => ['Damaturu', 'Potiskum', 'Gashua', 'Nguru', 'Geidam', 'Dapchi', 'Fika', 'Buni Yadi', 'Gujba', 'Jakusko', 'Karasuwa', 'Machina', 'Nangere', 'Tarmuwa', 'Yunusa', 'Bade', 'Bursari', 'Damaturu', 'Fune', 'Gujba', 'Jakusko', 'Karasuwa', 'Machina', 'Nangere', 'Nguru', 'Potiskum', 'Tarmuwa', 'Yunusa', 'Buni-Gari', 'Dawasa', 'Dumbulwa', 'Gadaka', 'Garandoili', 'Baiomari', 'Anguwar Kuka', 'Kofar M. Hudu', 'Anguwar Dutsi', 'Market Stall', 'Bakati S. Gari', 'Damagum', 'Fika', 'Gashua', 'Giedam', 'Nguru', 'Potiskum', 'Daura'],
        'Zamfara' => ['Gusau', 'Kaura Namoda', 'Talata Mafara', 'Anka', 'Bakura', 'Bungudu', 'Gummi', 'Maradun', 'Maru', 'Shinkafi', 'Tsafe', 'Zurmi', 'Bukkuyum', 'Birnin Magaji/Kiyaw', 'Chafe', 'Moriki', 'Sauri', 'Kiyaw', 'Magaji', 'Birnin', 'Dakube', 'Kaura', 'Namoda', 'Talata', 'Mafara', 'Gusau', 'Anka', 'Bakura', 'Bungudu', 'Gummi', 'Maradun', 'Maru', 'Shinkafi', 'Tsafe', 'Zurmi', 'Bukkuyum', 'Chafe'],
        'FCT' => ['Abuja', 'Gwagwalada', 'Kubwa', 'Kuje', 'Kwali', 'Abaji', 'Bwari', 'Garki', 'Asokoro', 'Central Area', 'Maitama', 'Wuse', 'Utako', 'Jabi', 'Lugbe', 'Nyanya', 'Karu', 'Maraba', 'Dutse', 'Gwarinpa', 'Kabusa', 'Dakibiyu', 'Duboyi', 'Galadimawa', 'Idu', 'Dawaki', 'Dei Dei', 'Durumi', 'Gishiri', 'Apo', 'Dutse Alhaji', 'Karmo', 'Lifecamp', 'Lokogoma', 'Katampe', 'Wuye', 'Gudu', 'Apo Mechanic Village', 'Byanzhin', 'Madalla'],
    ],
];